# Enable/disable functionality of this plugin.
enabled: true

# Configure which types of moving minecarts should load chunks.
minecarts:
  normal: false
  chest: true
  furnace: true
  tnt: true
  hopper: true
  spawner: true
  command-block: true

# Radius of the region of chunks around a moving minecart to load (in chunks).
# Region will be a square of side length (radius*2 + 1) with the minecart's current chunk in the center.
region-radius: 2

# How long to keep the region in which a minecart was last active in loaded after it stopped moving (in ticks).
keep-last-region-loaded-time: 600

# Whether to save the currently loaded regions at server shutdown and reload them again at the next startup.
# This ensures that all previously moving minecarts will immediately resume movement (even without nearby players loading their chunks first).
restore-regions-after-restart: true

# Minimum duration between checking positions of moving minecarts (in ticks).
# Might need to be decreased for maximum speeds higher than vanilla.
# This also defines the interval for how often to check for inactive regions that need to be unloaded.
update-interval: 8

# Threshold below which speed a minecart is considered to be stationary (in blocks per tick).
speed-threshold: 0.001

# Don't modify this.
config-version: 2
