name: '${project.name}'
version: '${project.version}'
main: '${project.groupId}.CartLoader'
api-version: '1.20.6'
description: 'A plugin enabling Minecarts to dynamically load chunks, ensuring seamless long-distance travel without player presence.'
author: YourMJK
website: https://github.com/YourMJK/CartLoader

depend: [NBTAPI]

commands:
  cartloader:
    description: All CartLoader subcommands
    permission: cartloader
    usage: /<command> (help|give)

permissions:
  cartloader:
    description: Allows the /cartloader command
    default: op
